"""changed character id in stories

Revision ID: 22eef2a9ce99
Revises: 86d03ffe3a92
Create Date: 2025-09-22 13:41:49.616166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22eef2a9ce99'
down_revision: Union[str, None] = '86d03ffe3a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('character_ids_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'character_ids_json')
    # ### end Alembic commands ###
