"""added user prompt to chapters

Revision ID: 26b8ab827ec2
Revises: f0f3d0bc780b
Create Date: 2025-10-11 11:27:55.064886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b8ab827ec2'
down_revision: Union[str, None] = 'f0f3d0bc780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('user_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'user_prompt')
    # ### end Alembic commands ###
