"""add image_cover

Revision ID: 2e4a97e4c034
Revises: 218d72b583b3
Create Date: 2025-09-15 13:34:17.207981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4a97e4c034'
down_revision: Union[str, None] = '218d72b583b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('cover_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'cover_image_url')
    # ### end Alembic commands ###
