"""Add phone to contact

Revision ID: 47c0405ffd64
Revises: 3e45bebf4871
Create Date: 2025-08-13 20:47:29.200656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c0405ffd64'
down_revision: Union[str, None] = '3e45bebf4871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone')
    # ### end Alembic commands ###
