"""init stories/chapters only

Revision ID: 4b9fa49ba84f
Revises: 1fc7b0db2869
Create Date: 2025-09-12 18:15:34.118345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9fa49ba84f'
down_revision: Union[str, None] = '1fc7b0db2869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
