"""add status stories

Revision ID: 6a543505432e
Revises: 2c3bcf64bd2d
Create Date: 2025-09-12 08:22:55.649076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a543505432e'
down_revision: Union[str, None] = '2c3bcf64bd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'status')
    # ### end Alembic commands ###
