"""added characters images in story

Revision ID: 73c4727811b1
Revises: b3c545af8127
Create Date: 2025-09-21 15:17:31.055217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c4727811b1'
down_revision: Union[str, None] = 'b3c545af8127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('character_images_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'character_images_json')
    # ### end Alembic commands ###
