"""changed character id in stories2

Revision ID: 8427814213b1
Revises: 22eef2a9ce99
Create Date: 2025-09-22 13:42:53.725149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8427814213b1'
down_revision: Union[str, None] = '22eef2a9ce99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'character_images_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('character_images_json', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
