"""added field name in characters table

Revision ID: 86d03ffe3a92
Revises: 55434d4b1c60
Create Date: 2025-09-22 08:53:39.361761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d03ffe3a92'
down_revision: Union[str, None] = '55434d4b1c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_images', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_images', 'name')
    # ### end Alembic commands ###
