"""added bible in story

Revision ID: 883a7448ab4e
Revises: 9731cf2e8f2a
Create Date: 2025-10-15 13:30:42.980877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883a7448ab4e'
down_revision: Union[str, None] = '9731cf2e8f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('bible_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'bible_json')
    # ### end Alembic commands ###
