"""added is_final to chapters

Revision ID: 9731cf2e8f2a
Revises: 26b8ab827ec2
Create Date: 2025-10-11 14:12:53.322385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9731cf2e8f2a'
down_revision: Union[str, None] = '26b8ab827ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'is_final')
    # ### end Alembic commands ###
