"""remove user_id in account_delete

Revision ID: b13fa02c87cc
Revises: c98aa6b15d26
Create Date: 2025-09-18 13:55:42.523430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13fa02c87cc'
down_revision: Union[str, None] = 'c98aa6b15d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_deletions_user_id', table_name='account_deletions')
    op.drop_constraint('account_deletions_user_id_fkey', 'account_deletions', type_='foreignkey')
    op.drop_column('account_deletions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_deletions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('account_deletions_user_id_fkey', 'account_deletions', 'users', ['user_id'], ['id'])
    op.create_index('ix_account_deletions_user_id', 'account_deletions', ['user_id'], unique=False)
    # ### end Alembic commands ###
