"""added language in story

Revision ID: f0f3d0bc780b
Revises: f28ae3670abb
Create Date: 2025-10-05 10:36:25.425723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f3d0bc780b'
down_revision: Union[str, None] = 'f28ae3670abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'language')
    # ### end Alembic commands ###
