"""added audio in chapter

Revision ID: f28ae3670abb
Revises: 8427814213b1
Create Date: 2025-10-04 19:40:49.276423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28ae3670abb'
down_revision: Union[str, None] = '8427814213b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'audio_url')
    # ### end Alembic commands ###
